// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/resource.proto

package com.google.api;

public final class ResourceProto {
  private ResourceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.google.api.ResourceProto.resource);
    registry.add(com.google.api.ResourceProto.resourceReference);
    registry.add(com.google.api.ResourceProto.resourceDefinition);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int RESOURCE_FIELD_NUMBER = 1053;
  /**
   * <pre>
   * A representation of the resource.
   * This is generally intended to be attached to the "name" field of
   * the message representing the resource.
   * Example:
   *     message Topic {
   *       string name = 1 [(google.api.resource) = {
   *         pattern: "projects/{project}/topics/{topic}"
   *       }];
   *     }
   * Only one of {`resource`, `resource_reference`} may be set.
   * </pre>
   *
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      com.google.api.Resource> resource = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.api.Resource.class,
        com.google.api.Resource.getDefaultInstance());
  public static final int RESOURCE_REFERENCE_FIELD_NUMBER = 1055;
  /**
   * <pre>
   * The fully qualified message name of the type that this field references.
   * Marks this as a field referring to a resource in another message.
   * Example:
   *   message Subscription {
   *     string topic = 2
   *       [(google.api.resource_reference) = "google.pubsub.v1.Topic"];
   *   }
   * If the referenced message is in the same proto package, the package
   * may be omitted:
   *   message Subscription {
   *     string topic = 2
   *       [(google.api.resource_reference) = "Topic"];
   *   }
   * Only one of {`resource`, `resource_reference`} may be set.
   * </pre>
   *
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> resourceReference = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int RESOURCE_DEFINITION_FIELD_NUMBER = 1053;
  /**
   * <pre>
   * A representation of a resource.
   * At a file level, this is generally used to define information for a
   * resource from another API, or for a resource that does not have an
   * associated proto message.
   * See the example of `google.api.Project` and `google.api.Organization`
   * at the bottom of this file.
   * </pre>
   *
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      java.util.List<com.google.api.Resource>> resourceDefinition = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.api.Resource.class,
        com.google.api.Resource.getDefaultInstance());
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_api_Resource_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_api_Resource_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031google/api/resource.proto\022\ngoogle.api\032" +
      " google/protobuf/descriptor.proto\"+\n\010Res" +
      "ource\022\017\n\007pattern\030\001 \001(\t\022\016\n\006symbol\030\002 \001(\t:F" +
      "\n\010resource\022\035.google.protobuf.FieldOption" +
      "s\030\235\010 \001(\0132\024.google.api.Resource::\n\022resour" +
      "ce_reference\022\035.google.protobuf.FieldOpti" +
      "ons\030\237\010 \001(\t:P\n\023resource_definition\022\034.goog" +
      "le.protobuf.FileOptions\030\235\010 \003(\0132\024.google." +
      "api.ResourceB\272\001\n\016com.google.apiB\rResourc" +
      "eProtoP\001ZAgoogle.golang.org/genproto/goo" +
      "gleapis/api/annotations;annotations\242\002\004GA" +
      "PI\352A\035\n\022projects/{project}\022\007Project\352A,\n\034o" +
      "rganizations/{organization}\022\014Organizatio" +
      "nb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
    internal_static_google_api_Resource_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_api_Resource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_api_Resource_descriptor,
        new java.lang.String[] { "Pattern", "Symbol", });
    resource.internalInit(descriptor.getExtensions().get(0));
    resourceReference.internalInit(descriptor.getExtensions().get(1));
    resourceDefinition.internalInit(descriptor.getExtensions().get(2));
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ResourceProto.resourceDefinition);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
